### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by cryer** [byungsook/deep-fluids#1]
Sorry to ask a question that seems to have nothing with this project,it seems there are something wrong with my mantaflow,but I dont know how to fix it.When I run smoke_pos_size.py,I got a error:
`NameError: name 'copyGridToArrayMAC' is not defined` ,not only copyGridToArrayMAC,but every function about numpy convert doesn't work. Have you ever met such problem?

PS:I have reinstalled mantaflow,same error just happens.

**Comment by cryer** [comment]
Sorry,it's solved.I have digged into the makefile and cmakelist,chaged some and it worked now,it seems it didn't compile some cpp flies.THX.

**Comment by dwidemann** [comment]
I'm running into the same problem. Could you please tell me what changes you made to cmakelist?

**Comment by vivanov879** [comment]
I encountered the same issue. The fix was to use NUMPY flag for cmake:

```bash
mkdir build
cd build
cmake .. -DGUI=OFF -DOPENMP=ON -DNUMPY=ON
make -j 8
```
