### ISSUE TITLE
How do you visualize the network output: velocity fields and density. 

### ISSUE THREAD

**Issue by vivanov879** [byungsook/deep-fluids#10]
Hi. How do you obtain the pretty video visualizations shown in the youtube video accompanying the paper? I tried plotting the velocity field images via matplotlib but I believe there is a better way to do this. Do you maybe export the mantaflow format to Blender somehow?

**Comment by byungsook** [comment]
Hi, you mean by 2d velocity plots, right? you can take a look at this function: https://github.com/byungsook/deep-fluids/blob/4b5dafa632022e874d2275af962ae0b3e9890f03/util.py#L175

**Comment by vivanov879** [comment]
Thanks for referencing the function. I actually meant rendered videos like this one:


<img width="320" alt="Screen Shot 2020-10-26 at 6 33 27 PM" src="https://user-images.githubusercontent.com/598178/97200596-16466480-17ba-11eb-8b36-f649ceaed5d8.png">

**Comment by byungsook** [comment]
There are several off-the-shelf products like houdini, maya or blender, and I used maya for this project. Once numpy arrays are converted to openvdb format (for instance by passing through manta or using pyopenvdb), it should be easy to load it from any of them.

**Comment by vivanov879** [comment]
@byungsook,  thanks for the tip :)
