### ISSUE TITLE
Velocity field -> density

### ISSUE THREAD

**Issue by vivanov879** [byungsook/deep-fluids#11]
Hi @byungsook. Can you please clarify one point for me: is it possible to move from velocity field to density? While reading the Deep Fluids paper, I noticed that the main focus is the velocity field. However, I can't grasp how to move from a velocity field to density. For example, the "Algorithm 1, Simulation with the Latent Space Integration Network" is about velocity field generation. However, the rendered images shown in the paper Figures 8, 9, 10, 11 are all obtained via rendering. Is it possible to make Maya/Blender render with only velocity fields, or is there some explicit way of getting density out of velocity fields for rendering?

**Comment by byungsook** [comment]
Hi @vivanov879, you have to advect density fields by reconstructed velocity fields. Please check this code: https://github.com/byungsook/deep-fluids/blob/master/scene/smoke3_vel_buo.py#L49

**Comment by vivanov879** [comment]
Now I see, thanks for the quick response.
