### ISSUE TITLE
Why is Algorithm 1 faster than integrating ODE? 

### ISSUE THREAD

**Issue by vivanov879** [byungsook/deep-fluids#12]
Hi @byungsook. Can you please provide intuition why is Algorithm 1 "Simulation with the Latent Space Integration Network
" would be faster than integrating the ODE that obey the inviscid momentum `Du/Dt = −∇ p + g` and mass conservation `∇ · u = 0` equations? To me, it's like you have all the formulas and can integrate them. While a neural network introduces multiple layers which will take far more time.

**Comment by byungsook** [comment]
Hi @vivanov879, some parts of integration for fluid simulation is computationally expensive (e.g., pressure poisson solver), while mlp evaluation is more or less constant. Please refer to https://www.cs.ubc.ca/~rbridson/fluidsimulation/.

**Comment by vivanov879** [comment]
Ok, I will take a look, thanks.
