### ISSUE TITLE
Torch implementation

### ISSUE THREAD

**Issue by vivanov879** [byungsook/deep-fluids#14]
Hi @byungsook. I reimplemented 3d smoke experiments in PyTorch in my fork of your project https://github.com/vivanov879/deep-fluids. I also described the experiments and my analysis of the results in the paper https://github.com/vivanov879/deep-fluids/blob/master/PyTorch%20implementation%20of%20Deep%20Fluids.pdf. Feel free to share your thoughts on that and thanks for the awesome project.

**Comment by byungsook** [comment]
Hi @vivanov879, good to know that you implemented a pytorch implementation. I will have a look, and thanks for your interest in this project.

**Comment by vivanov879** [comment]
Thank you so much for explaining a whole lot regarding you work.
