### ISSUE TITLE
problem in manta

### ISSUE THREAD

**Issue by Nimava** [byungsook/deep-fluids#2]
Thanks for your nice code. I have a problem in running manta on linux. I followed the instruction and installed manta. When I run the test case: ` ./manta ../scenes/simpleplume.py`. I have a message: 
```
Version: mantaflow 0.12 64bit fp1 omp commit 15eaf4aa72da62e174df6c01f85ccd66fde20acc from Sep 25 2019, 15:17:48
QXcbConnection: Could not connect to display 
Aborted (core dumped)
```
I changed the Cmake to: `cmake .. -DGUI=OFF -DOPENMP=ON -DNUMPY=ON`
but nothing changed. I remote to the Red Hat 4.4.7-23, Do you have any idea?

**Comment by byungsook** [comment]
I think it should work with -DGUI=OFF option cause it seems Qt is the issue in your environment.
You can reinstall qt and try again. I hope it helps.

**Comment by Nimava** [comment]
Thanks for your answer. You are right. I rebuild the code and now it works.
