### ISSUE TITLE
copyGridToArrayMAC(vel, v_) Dimensions do not match Error 

### ISSUE THREAD

**Issue by hassaniqbal209** [byungsook/deep-fluids#20]
After successfully installing and running mantaflow, I try to run the data generation script by entering the command: 

$ ..\manta\build\Release\manta.exe .\scene\smoke_pos_size.py

However, I receive the following error:
Error in copyGridToArrayMAC
sim:   0%|                                                                                                         | 0/200 [00:00<?, ?it/s]
scenes:   0%|                                                                                                      | 0/105 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "scene/smoke_pos_size.py", line 259, in <module>
    main()
  File "scene/smoke_pos_size.py", line 199, in main
    copyGridToArrayMAC(vel, v_)
RuntimeError: The dimensions of source grid (96, 128, 1) and target numpy array (3, 96, 128) do not match!
Error raised in /workdir/manta/source/plugin/numpyconvert.cpp:122
Script finished.

While installing, I deviated from original guidelines in readme.md at two points:
1. Install tensorflow version 2.11 instead of 1.15 since the later is incompatible with my python version 3.9
2. Installed manta with 'master' branch instead of '15eaf4' since the latter was giving the error 'ImportError: numpy.core.multiarray failed to import' even with DNUMPY=ON

Would be grateful if someone can guide on how to resolve this issue.

**Comment by lukegreen2000** [comment]
I am having this same error and dont know how to fix it, I have noticed you have upgraded to tensorflow 2.11 without updating the tensorflow code though. Tensorflow 2.x and Tensorflow 1.x are entirely different and wont work together. In order to use an incompatible version of tensorflow you would be better using NVIDEA tf. I found this tutorial handy. https://www.pugetsystems.com/labs/hpc/How-To-Install-TensorFlow-1-15-for-NVIDIA-RTX30-GPUs-without-docker-or-CUDA-install-2005/#Installing_NVIDIAs_build_of_TensorFlow_115_in_a_conda_env

**Comment by lukegreen2000** [comment]
So after maybe a month on and off trying at this problem I just fixed it, in the file numpyconvert,cpp the assert message is just wrong I have no idea why but when running a 2D model it just doesnt work 

change the lines 121 and 122 in this file from:

assertMsg(target.TotalSize == uSizeX * uSizeY * uSizeZ * uSizeW, "The size of the numpy array doesn't match the size of the grid!");
	assertMsg(target.Dims[0] == uSizeZ && target.Dims[1] == uSizeY && target.Dims[2] == uSizeX, "The dimensions of source grid ("+to_string(uSizeX)+", "+to_string(uSizeY)+", "+to_string(uSizeZ)+") and target numpy array ("+to_string(target.Dims[2])+", "+to_string(target.Dims[1])+", "+to_string(target.Dims[0])+") do not match!");

to: 

assertMsg(target.TotalSize == uSizeX * uSizeY * uSizeZ * uSizeW, "The size of the numpy array doesn't match the size of the grid!");
	assertMsg(target.Dims[2] == uSizeW && target.Dims[0] == uSizeY && target.Dims[1] == uSizeX, "The dimensions of source grid ("+to_string(uSizeX)+", "+to_string(uSizeY)+", "+to_string(uSizeZ)+") and target numpy array ("+to_string(target.Dims[2])+", "+to_string(target.Dims[1])+", "+to_string(target.Dims[0])+") do not match!");

im not sure if this is a hacky solution but it works for 2d models. If this does not work for 3d just make a new function called copygridtoarraymac3d and copy the original code into that and it should produce a working 3d effort

**Comment by lukegreen2000** [comment]
Actually Im pretty sure you can just remove the assert all together honestly as it just doesnt work for both 2d and 3d

**Comment by hassaniqbal209** [comment]
@lukegreen2000 thank you for your effort in fixing this. It's working for me for the 2D case. Your comment is noted about the 3D case and assert command. I can test it once I move on to 3D. Thank you again for your time and effort.
