### ISSUE TITLE
Any plans to release pre-trained weights?

### ISSUE THREAD

**Issue by Kshitij-Khode** [byungsook/deep-fluids#5]
I was wondering if there's any plans for releasing some pre-trained weights or checkpoints for a partially trained network?

I'm currently training the model with data generated by ./scene/smoke_pos_size.py, but it'd be nice if access to pre-trained weights was provided.

**Comment by byungsook** [comment]
Thanks for your interests in our project. For now, there is no plan to release pre-trained network

**Comment by shehreenmushtaq** [comment]
Can we get pre-trained model if possible. Thanks
