### ISSUE TITLE
Different normalization for training and test data

### ISSUE THREAD

**Issue by IvanEz** [byungsook/deep-fluids#7]
@byungsook could you please explain why we have different normalization for training and test data?
in data.py in line 332 we normalize "y" variable by:
```
for i, ri in enumerate(y_range): 
    y[i] = (y[i]-ri[0]) / (ri[1]-ri[0]) * 2 - 1
```
whereas in trainer.py in line 327 we have:
```
c1 = p1/float(y1-1)*2-1
c2 = p2/float(y2-1)*2-1
```

In plain language, in the first case we have: (p_current - p_min)/(p_max - p_min)*2 - 1 
and in the second: p_current/(p_number_of_values - 1)*2 - 1

**Comment by byungsook** [comment]
Hi, the first one is to normalize the value by its range, e.g.,
https://github.com/byungsook/deep-fluids/blob/0f6ab95f1352713de294bac5b013ac2d9883185e/scene/smoke_pos_size.py#L23-L24

and the second one is to get the normalized value from its index, e.g.,
https://github.com/byungsook/deep-fluids/blob/0f6ab95f1352713de294bac5b013ac2d9883185e/scene/smoke_pos_size.py#L22
where p1, p2 = 10, 2, y1=21, y2=5 (i.e., 11th xpos, 3rd radius).
