### ISSUE TITLE
Input pipeline: batches created without 'replacing'

### ISSUE THREAD

**Issue by tudormot** [byungsook/deep-fluids#8]
Hello,
As far as I can tell, when reading input data from file and enqueuing it in the FIFO (from where batches are dequeued), the code does it by sampling from a uniform distribution with replacing (data.py, line 128). Is there any reason why sampling without replacement was not used? I think sampling without replacement is the common practice, this way all the data is guaranteed to be 'seen' once in each epoch, leading to better training in the short run

Thank you!

edited: replaced 'with' with 'without', sorry for the confusion

**Comment by byungsook** [comment]
Hi, I agree that sampling without replacement is ideally better in the short run.
In our case, many epochs are required to train the network, hence the current code won't show much difference in the final performance.

**Comment by tudormot** [comment]
Hi @byungsook ,
many thanks for the response! Yes, you are right for long training it should not quite matter.Sorry a quick last question, unfortunately I am also not able to get as fast inference time as you mention in the paper. Essentially, I am using exactly your implementation for training and test, and to measure the time I do (in line 340 in trainer.py):

`for b in range(niter):
            start=time.time()
            G_ = self.sess.run(self.G_, {self.z: z_c[self.test_b_num*b:self.test_b_num*(b+1),:]})
            G_, _ = self.batch_manager.denorm(x=G_)
            end=time.time()
            print(end-start)`

This gives me on average between 150 and 300 ms on different smoke datasets while you have around 1 ms. I am using a Tesla P100-PCIE GPU, which shouldn't be very different from what you have used..
Could you tell me what is the catch I am missing? 

Thanks,
Tudor

**Comment by byungsook** [comment]
Duplicate of #9.

**Comment by byungsook** [comment]
Please take a look at #9
