### ISSUE TITLE
Computing the evaluation time

### ISSUE THREAD

**Issue by IvanEz** [byungsook/deep-fluids#9]
Hi @byungsook ,
sorry, I am a bit struggling to reproduce the exact evaluation time you reported in the paper (0.958 ms for a batch of size 5 for the "smoke inflow" dataset). Get about two orders higher time ~ 200 ms.
Could you please share how did you measure the time? Did you call time.time() inside the test_() function in the trainer.py? Did you compute it for a single batch or you ran multiple batches and took an average thereof? Thank you a lot!

**Comment by neuronflow** [comment]
+1 unfortunately I also fail to replicate your results with similar results as @IvanEz . Thank you in advance for looking into this.

**Comment by byungsook** [comment]
Hi all, 
I think I lost my old code for profiling while refactoring.
As I remember, the profiling was done as below:
https://towardsdatascience.com/howto-profile-tensorflow-1a49fb18073d
Then, only the computation part was considered and averaged without IO somehow.
Sorry but I hope it helps.

**Comment by IvanEz** [comment]
Thank you!
